name: demo_tm
description: An example application for TimeMachine.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  tm:
    path: ../

  web3_icons: ^0.0.8
  google_fonts: ^3.0.1
  url_launcher: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
